name: 'Build'

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: yarn

      - name: Yarn
        run: yarn install --frozen-lockfile

      - name: next build
        run: yarn build

